rm(list=ls())

require(rgdal)
require(maptools)
require(plyr)
require(ggplot2)
require(raster)
require(sp)
require(rgeos)
require(colorRamps)

project <- TRUE
setwd("/media/dcyr/Windows7_OS/Travail/SCF/InsectClimatePotential")
processedOutputs <- "./processedOutputs"
outputDir <- paste(getwd(), Sys.Date(), sep="/")
dir.create(outputDir)

figFolder <- paste(outputDir, "Figures", sep="/")
dir.create(figFolder)
############################
############################
####  Identifying input data
####  (previously formatted by 'climInsectOutputsToDF.R' from biosim outputs)
outputFiles <- list.files(processedOutputs)
stackFiles <- outputFiles[grep(".RData", outputFiles)]
##
stackInfo <- strsplit(stackFiles, "_")
spp <- unlist(lapply(stackInfo, function(x) x[1]))
stackNames <- unlist(lapply(stackInfo, function(x) x[2]))
stackNames <- gsub(".RData", "", stackNames)


############################
############################
####  Loading some rasters and shapefiles
####  Previously generated by 'sigPrep.R'
can_usF <- get(load("./gis/can_usF.RData"))
can_usRas <- get(load("./gis/can_usRas.RData"))
ecoregionRas <- get(load("./gis/ecoregionRas.RData"))
ecoregionRas[is.na(can_usRas)] <- NA



### plotting (+ other things)
for (i in c(5:7)) {#},5:7)) {#seq_along(stackFiles)) {
    r <- get(load(paste(processedOutputs, stackFiles[i], sep="/")))
    layerNames <-  gsub("\\.", "_", names(r))
    varName <- unique(gsub("[^A-z]|_", "", layerNames))
    if (project) {
        r <- projectRaster(r, crs = CRS("+init=epsg:2163") )
    }

    ###
    # some cleaning up is probably necessary (remove NA values, etc.)
    ###

    r <- resample(r, can_usRas, method='bilinear')
    r[is.na(can_usRas)] <- NA  ## way too long... don't know why
    names(r) <- layerNames

    sp <- spp[i]
    ###
    if (sp == "FTC") {
        zmin <- floor(min(minValue(r), na.rm=T)/10)*10
        zmax <- min(ceiling(max(maxValue(r), na.rm=T)/10)*10, 365)
        cols <- rev(matlab.like2(5))
        vName <- "Julian day"
        descrip <- ""
    }
    if (sp == "MPB") {
        zmin <- 0
        zmax <- 1
        cols <- matlab.like2(5)
        vName <- "Probability"
        if (varName == "ColdToleranceSurvival") {
            descrip <-  "Variable description:\nLikelihood of larvae winter survival"
        }
        if (varName == "LoganProbability") {
            descrip <-  "Variable description:\nAdaptive seasonality - Likelihood of a synchonized univoltine life cycle"
        }
        if (varName == "SafranyikProbability") {
            descrip <-  "Variable description:\nJoint likelihood of a univoltine life cycle, over-winter survival, optimal\nemergence/dispersal conditions, and adequacy of spring precipitation"
        }

    }
    if (sp == "SBW") {
        zmin <- floor(min(minValue(r), na.rm=T))
        zmax <- ceiling(max(maxValue(r), na.rm=T))
        cols <- matlab.like2(5)
        vName <- "Growth Rate"
        descrip <- "Variable description:\nPopulation potential growth rate index"
    }
    at <- pretty(zmax:zmin)
    ###


    ### preparing cluster
    require(foreach)
    require(doSNOW)
    #
    clusterN <- 3
    cl = makeCluster(clusterN)
    #
    registerDoSNOW(cl)

    animateIndex <- foreach(l = 1:nlayers(r), .combine = 'c')  %dopar% {#
        require(raster)
        require(ggplot2)

        fName <- paste0(figFolder, "/", sp, "_", layerNames[l],".png")

        #if (sp == "FTC") {

        #vName <- strsplit(layerNames[l], "_")[[1]][1]
        #}
#         if (sp == "MPB") {
#             vName <- "ColdToleranceSurvival"
#         }



        #######################
        ## transforming raster to standard data frame
        mapP <- rasterToPoints(r[[l]])
        df <- data.frame(mapP)
        #######################

        p <- ggplot(data = df, aes_string("x", "y", fill = colnames(df)[3])) +
            theme_bw() +
            geom_raster() +
            coord_equal() +
            scale_fill_gradientn(vName, limits=c(zmin,zmax),
                                 colours = cols) +
            theme(legend.position=c(0.15, 0.3),
                  legend.direction = "vertical",
                  axis.line=element_blank(),axis.text.x=element_blank(),
                  axis.text.y=element_blank(),axis.ticks=element_blank(),
                  axis.title.x=element_blank(),
                  axis.title.y=element_blank(),
                  panel.background=element_blank(),panel.border=element_blank(),panel.grid.major=element_blank(),
                  panel.grid.minor=element_blank(),plot.background=element_blank()) +
            #"bottom") +

            geom_polygon(data = can_usF, aes(x = long, y = lat,  group = group), colour="black", fill = NA) +
            labs(title = paste0(sp, " ", gsub("_", " ", layerNames[l]), "\n"),
                 y="",
                 x="") +
            scale_x_continuous(breaks=NULL) +
            scale_y_continuous(breaks=NULL) +
            annotate("text", x = min(df[,"x"]), y = min(df[,"y"])-0.10*(diff(range(df[,"y"]))), label = descrip,
                     size = 3.5, hjust = 0)

        ##############################



        png(filename = fName, width = 480, height = 480)
            print(p)
        dev.off()

        if (is.finite(max(values(r[[l]]), na.rm = T))) {
            return(l)
        }

    }
    stopCluster(cl)


    ### preparing files for animated GIFs
    fileNames <- paste0(figFolder, "/", sp, "_", layerNames[animateIndex],".png")
    ##
    require(animation)
    interval <- ifelse(length(fileNames) > 30, 0.5, 0.75)
    oopt = ani.options(ani.dev="png", ani.type="png", interval = interval, autobrowse = FALSE)
    animName <- paste(gsub(".RData", "", stackFiles[i]) , sep = "_")

    im.convert(fileNames, output = paste0(figFolder, "/", animName, ".gif"), #convert = c("convert", "gm convert"),
               extra.opts = "", clean = FALSE)

}

