rm(list=ls())

#require(rgdal)
#require(maptools)
#require(plyr)
#require(ggplot2)
require(raster)
require(dplyr)
#require(sp)
#require(rgeos)
#require(colorRamps)
require(reshape2)

regions <- "Ecozone" # can be either 'Ecozone' or 'Ecoregion'
project <- TRUE ### keep this true

setwd("/media/dcyr/Windows7_OS/Travail/SCF/InsectClimatePotential")
processedOutputs <- "./processedOutputs"
outputDir <- paste(getwd(), Sys.Date(), sep="/")
dir.create(outputDir)

############################
############################
####  Identifying input data
####  (previously formatted by 'climInsectOutputsToDF.R' from biosim outputs)
outputFiles <- list.files(processedOutputs)
stackFiles <- outputFiles[grep(".RData", outputFiles)]
##
stackInfo <- strsplit(stackFiles, "_")
spp <- unlist(lapply(stackInfo, function(x) x[1]))
stackNames <- unlist(lapply(stackInfo, function(x) x[2]))
stackNames <- gsub(".RData", "", stackNames)


############################
############################
####  Loading some rasters and shapefiles
####  Previously generated by 'sigPrep.R'
can_usF <- get(load("./gis/can_usF.RData"))
can_usRas <- get(load("./gis/can_usRas.RData"))
ecoregionRas <- get(load("./gis/ecoregionRas.RData"))
ecoregionRas[is.na(can_usRas)] <- NA

### switching attribute for regional partitionning
switch_att <- function(r, att) {
    r[] <- levels(r)[[1]][values(r), att]
    return(r)
}
###
if (regions == "Ecozone") {
    regionRas <- switch_att(ecoregionRas, "ZONE_NAME")
}
if (regions == "Ecoregion") {
    regionRas <- switch_att(ecoregionRas, "REGION_NAM")
}
rat <- levels(regionRas)[[1]]


### creating data frame containing regionnaly partitionned time series
### preparing cluster
require(foreach)
require(doSNOW)
#
clusterN <- 3
cl = makeCluster(clusterN)
#
registerDoSNOW(cl)
#
regionalOutputs <- foreach(i = seq_along(stackNames))  %dopar% {#
    require(raster)
    require(reshape2)

    r <- get(load(paste(processedOutputs, stackFiles[i], sep="/")))
    layerNames <-  gsub("\\.", "_", names(r))
    varName <- unique(gsub("[^A-z]|_", "", layerNames))
    sp <- spp[i]
    if (project) {
        r <- projectRaster(r, crs = CRS("+init=epsg:2163") )
    }

    # resampling
    r <- resample(r, regionRas, method='bilinear')
    r[is.na(regionRas)] <- NA
    names(r) <- layerNames


    df <- as.data.frame(zonal(r, regionRas, fun = "mean", na.rm = T))

    df <- melt(df, id.vars = "zone", measure.vars = colnames(df)[grep(varName, colnames(df))])
    df[,"year"] <- as.numeric(gsub("[A-z]|_", "", df$variable))
    df[,"variable"] <- gsub("[^A-z]|_", "", df$variable)
    df[, paste0(regions, "Name")] <- rat[df$zone, "VALUE"]

    ## final cleaning up
    if (regions == "Ecozone") {
        df <- df[,c("year", "variable", "EcozoneName",  "value")]
    }
    if (regions == "Ecoregion") {
        df <- df[,c("year", "variable", "EcoregionName",  "value")]
    }
    return(df)
}
stopCluster(cl)


for (sp in unique(spp)) {
    spIndex <- grep(sp, spp)
    df <- regionalOutputs[spIndex]
    df <- bind_rows(df)
    dfName <- paste(sp, regions, sep= "_")
    assign(dfName, as.data.frame(df))
    save(list = dfName, file = paste0(outputDir, "/", dfName,".RData"))
}


